apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  #namespace: ${WORKLOAD_NAMESPACE}
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: local-rabbit
    #namespace: ${WORKLOAD_NAMESPACE}
