apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vmclone
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/davlloyd/vm-clone:5
          env:
            - name: VC_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: vsphere-credentials
                  key: username
            - name: VC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vsphere-credentials
                  key: password
