apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vmrequest
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/davlloyd/git-vmrequest:15
