apiVersion: v1
kind: Secret
metadata:
  name: slack-hook
type: Opaque
data:
  slack_webhook: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAyNEpGVE40L0IwMkIzTks4OTQ2L3pWTFlablZIbVd1VVRZMjBMU2lNazZ3aw==
