apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: vmclone-sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: vmclone
  reply:
    ref:
      kind: Service
      apiVersion: serving.knative.dev/v1
      name: slack-notify